let practiceList = [
    {item: 'milk',
    quantity: '1',
    units: 'gal',
    notes: 'skim',
    stores:  ['Publix', 'Whole Foods']},
    {item: 'bread',
    quantity: '2',
    units: '',
    notes: 'wheat',
    stores: ['Publix', '7-11']},
    {item: 'cheese',
    quantity: '3',
    units: '',
    notes: 'swiss',
    stores: ['Whole Foods']},
    {item: 'cherries',
    quantity: '2',
    units: 'lbs',
    notes: 'organic',
    stores: ['Whole Foods', 'Publix']},
    {item: 'carrots',
    quantity: '1',
    units: 'lb',
    notes: 'baby carrots',
    stores: ['Publix']},
    {item: 'coffee',
    quantity: '1',
    units: 'lb',
    notes: 'NOT DECAF',
    stores: ['Publix']},
    {item: 'ice cream',
    quantity: '1',
    units: 'gal',
    notes: 'vanilla',
    stores: ['Publix', '7-11', 'Whole Foods']},
    {item: 'oranges',
    quantity: '5',
    units: '',
    notes: '',
    stores: ['Whole Foods']}
];
 export default practiceList;